version: '3.4'

services:
  ai-research-service:
    build:
      context: ./backend/AIResearchService
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Assuming AIResearchService runs on port 80 inside the container

  blazor-frontend:
    build:
      context: ./frontend/BlazorFrontend/BlazorFrontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"  # Serve the Blazor WASM app

  blazor-frontend-client:
    build:
      context: ./frontend/BlazorFrontend/BlazorFrontend.Client
      dockerfile: Dockerfile
    ports:
      - "8083:80"  # Serve the Blazor WASM client

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
