services:
  ai-research-service:
    build:
      context: ./backend/AIResearchService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - ai-research-network

  blazor-frontend:
    build:
      context: ./frontend/BlazorFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - ai-research-network

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ai-research-network

networks:
  ai-research-network:
    driver: bridge
